on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@master
      # Build & deploy
      - name: Deploy
        uses: shalzz/zola-deploy-action@v0.12.0
        env:
          # Target branch
          PAGES_BRANCH: master
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: https://github.com/varlociraptor/varlociraptor.github.io.git
