on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@master
      # Build & deploy
      - name: Deploy
        uses: shalzz/zola-deploy-action@v0.12.2
        env:
          REPOSITORY: "varlociraptor/varlociraptor.github.io"
          # Target branch
          PAGES_BRANCH: master
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
